name: start subfoldersync-vibe

on:
  workflow_call:
    inputs:
        source_repo:
            description: 'The repository to sync from, e.g., IMOitself/A'
            required: true
            type: string
        destination_repo:
            description: 'The repository to sync to, e.g., IMOitself/B'
            required: true
            type: string
        subfolder_path:
            description: 'The path to the subfolder to sync'
            required: true
            type: string
        username:
            description: 'The GitHub username to use for commits'
            required: true
            type: string
    secrets:
        gh_pat:
            description: 'A GitHub PAT with repo write access'
            required: true

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: Install git-filter-repo
              run: pip install git-filter-repo

            - name: Clone subfoldersync-vibe repo
              uses: actions/checkout@v4
              with:
                repository: 'IMOitself/subfoldersync-vibe'
                path: subfoldersync-vibe

            - name: Run sync script
              env:
                SOURCE_REPO: ${{ inputs.source_repo }}
                DEST_REPO: ${{ inputs.destination_repo }}
                SUBFOLDER_PATH: ${{ inputs.subfolder_path }}
                USERNAME: ${{ inputs.username }}
                GH_PAT: ${{ secrets.gh_pat }}
              run: |
                chmod +x subfoldersync-vibe/sync-subfolders.sh
                subfoldersync-vibe/sync-subfolders.sh
